# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - wmscope

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master


    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        
    - name: Build database configuration
      run: |
           ls -l
           echo -e "[client]" >> db_config.cnf
           echo -e "host = ${{secrets.DEVHOST}}" >> db_config.cnf
           echo -e "database = ${{secrets.DEVDATABASE}}" >> db_config.cnf
           echo -e "user = ${{secrets.DEVUSER}}" >> db_config.cnf
           echo -e "password = ${{secrets.DEVPASSWORD}}" >> db_config.cnf
           echo -e "default-character-set = utf8" >> db_config.cnf
           cd reqCore
           echo -e "[client]" >> db_config.cnf
           echo -e "host = ${{secrets.DEVHOST}}" >> db_config.cnf
           echo -e "database = ${{secrets.DEVDATABASE}}" >> db_config.cnf
           echo -e "user = ${{secrets.DEVUSER}}" >> db_config.cnf
           echo -e "password = ${{secrets.DEVPASSWORD}}" >> db_config.cnf
           echo -e "default-character-set = utf8" >> db_config.cnf

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.6'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wmscope'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_11b011a1f1ec4135b60c11b1ccb1bd64 }}
