on:
  workflow_dispatch
name: Deploy Dev Environment
jobs:
  deployTest:
      name: Build docker image
      runs-on: ubuntu-latest
      #container: python:3.8-slim
      steps:
      - name: Retrieve Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
             ls -l
             cd core
             pip3 install wheel
             pip3 install setuptools
             pip3 install -r requirements.txt
             echo -e "[client]" >> db_config.cnf
             echo -e "host = ${{secrets.DEVHOST}}" >> db_config.cnf
             echo -e "database = ${{secrets.DEVDATABASE}}" >> db_config.cnf
             echo -e "user = ${{secrets.DEVUSER}}" >> db_config.cnf
             echo -e "password = ${{secrets.DEVPASSWORD}}" >> db_config.cnf
             echo -e "default-character-set = utf8" >> db_config.cnf

      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Launch Django Server
        run: |
             echo ${{ steps.ip.outputs.ipv4 }}
             python3 manage.py runserver