on:
  workflow_dispatch
name: Deploy Test Host for Development
jobs:
  deployTest:
  timeout-minutes: 5
      name: Create Temporary Django Host
      runs-on: ubuntu-latest
      #container: python:3.8-slim
      steps:
      - name: Retrieve Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
             ls -l
             cd core
             pip3 install wheel
             pip3 install setuptools
             pip3 install -r requirements.txt
             echo -e "[client]" >> db_config.cnf
             echo -e "host = ${{secrets.DEVHOST}}" >> db_config.cnf
             echo -e "database = ${{secrets.DEVDATABASE}}" >> db_config.cnf
             echo -e "user = ${{secrets.DEVUSER}}" >> db_config.cnf
             echo -e "password = ${{secrets.DEVPASSWORD}}" >> db_config.cnf
             echo -e "default-character-set = utf8" >> db_config.cnf

      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Build using AppService-Build
        uses: azure/appservice-build@v1
        with:
          platform: python

      - name: Deploy Dev
        uses: azure/webapps-deploy@v1
        with:
          app-name: freebergPythonOryx
          publish-profile: ${{ secrets.PUB_PROF_ORYX_WEBAPP }}